ALTER TABLE candidate_profiles ADD COLUMN tenth_percentage NUMERIC(5,2);
ALTER TABLE candidate_profiles ADD COLUMN twelfth_percentage NUMERIC(5,2);
ALTER TABLE candidate_profiles ADD COLUMN physics_marks NUMERIC(5,2);
ALTER TABLE candidate_profiles ADD COLUMN mathematics_marks NUMERIC(5,2);
ALTER TABLE candidate_profiles ADD COLUMN english_marks NUMERIC(5,2);
ALTER TABLE candidate_profiles ADD COLUMN graduation_details VARCHAR(250);
ALTER TABLE candidate_profiles ADD COLUMN medical_status VARCHAR(40);
ALTER TABLE candidate_profiles ADD COLUMN flying_experience VARCHAR(250);
ALTER TABLE candidate_profiles ADD COLUMN total_flight_hours INTEGER;
ALTER TABLE candidate_profiles ADD COLUMN previous_aviation_training VARCHAR(250);
ALTER TABLE candidate_profiles ADD COLUMN english_proficiency VARCHAR(40);
ALTER TABLE candidate_profiles ADD COLUMN passport_available BOOLEAN;
ALTER TABLE candidate_profiles ADD COLUMN preferred_program VARCHAR(120);
ALTER TABLE candidate_profiles ADD COLUMN preferred_training_location VARCHAR(120);
ALTER TABLE candidate_profiles ADD COLUMN preferred_airline VARCHAR(120);
ALTER TABLE candidate_profiles ADD COLUMN available_from DATE;

CREATE TABLE cadet_programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    organisation VARCHAR(160) NOT NULL,
    description TEXT NOT NULL,
    training_location VARCHAR(160) NOT NULL,
    duration_months INTEGER NOT NULL,
    estimated_cost NUMERIC(12,2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    min_age INTEGER NOT NULL,
    max_age INTEGER NOT NULL,
    min_twelfth_percentage NUMERIC(5,2) NOT NULL,
    min_physics_marks NUMERIC(5,2) NOT NULL,
    min_mathematics_marks NUMERIC(5,2) NOT NULL,
    min_english_marks NUMERIC(5,2) NOT NULL,
    medical_required BOOLEAN NOT NULL,
    passport_required BOOLEAN NOT NULL,
    application_deadline DATE NOT NULL,
    selection_stages TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT ck_program_ages CHECK (min_age <= max_age)
);

CREATE TABLE eligibility_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL,
    program_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    checks_json TEXT NOT NULL,
    checked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_eligibility_candidate FOREIGN KEY (candidate_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_eligibility_program FOREIGN KEY (program_id) REFERENCES cadet_programs(id) ON DELETE CASCADE
);

CREATE INDEX idx_program_status ON cadet_programs(status);
CREATE INDEX idx_program_location ON cadet_programs(training_location);
CREATE INDEX idx_eligibility_candidate ON eligibility_results(candidate_id, program_id, checked_at);

INSERT INTO cadet_programs (code, name, organisation, description, training_location, duration_months, estimated_cost, currency, min_age, max_age, min_twelfth_percentage, min_physics_marks, min_mathematics_marks, min_english_marks, medical_required, passport_required, application_deadline, selection_stages, status) VALUES
('ACP-01', 'Airline Cadet Pilot Program', 'AeroVista Training Academy — Demo', 'A structured ab-initio pathway with ground school, simulator training and supervised flight phases.', 'Hyderabad, India', 18, 6800000.00, 'INR', 18, 25, 60.00, 60.00, 60.00, 60.00, TRUE, TRUE, '2026-11-30', 'Application|Eligibility|Aptitude Test|Technical Assessment|Interview|Medical|Final Selection', 'OPEN'),
('ICPP-02', 'Integrated Commercial Pilot Program', 'BlueWing Flight School — Demo', 'An integrated commercial pilot curriculum designed for candidates beginning without prior flight time.', 'Bengaluru, India', 20, 7200000.00, 'INR', 18, 28, 55.00, 55.00, 55.00, 55.00, TRUE, TRUE, '2026-12-15', 'Application|Eligibility|Aptitude Test|Interview|Medical|Final Selection', 'OPEN'),
('ASCP-03', 'Airline Sponsored Cadet Program', 'SkyBridge Aviation Group — Demo', 'A fictional sponsored pathway combining selection preparation, type-focused training and mentoring.', 'Mumbai, India', 22, 7800000.00, 'INR', 18, 24, 65.00, 65.00, 65.00, 60.00, TRUE, TRUE, '2027-01-10', 'Application|Eligibility|Aptitude Test|Group Exercise|Interview|Medical|Final Selection', 'UPCOMING'),
('IFTP-04', 'International Flight Training Program', 'Horizon Aviation Institute — Demo', 'A cross-border training pathway with international ground school and multi-environment flight exposure.', 'Dubai, UAE', 22, 385000.00, 'AED', 18, 28, 60.00, 60.00, 60.00, 60.00, TRUE, TRUE, '2027-01-12', 'Application|Eligibility|English Assessment|Technical Assessment|Interview|Medical|Final Selection', 'OPEN'),
('MCC-05', 'Multi-Crew Pilot Training Program', 'Altair Crew Academy — Demo', 'A competency-focused multi-crew pathway emphasising coordination, jet orientation and simulator practice.', 'Delhi NCR, India', 19, 7450000.00, 'INR', 18, 26, 60.00, 55.00, 60.00, 60.00, TRUE, TRUE, '2026-12-20', 'Application|Eligibility|Aptitude Test|Simulator Assessment|Interview|Medical|Final Selection', 'OPEN'),
('WFA-06', 'Women in Flight Cadet Pathway', 'Aquila Aviation Foundation — Demo', 'A fictional inclusive cadet pathway featuring mentoring, scholarships and an integrated CPL syllabus.', 'Pune, India', 21, 6400000.00, 'INR', 18, 29, 55.00, 55.00, 55.00, 55.00, TRUE, TRUE, '2027-02-05', 'Application|Eligibility|Aptitude Test|Interview|Medical|Final Selection', 'UPCOMING'),
('RCP-07', 'Regional Airline Cadet Program', 'Coastal Wings Academy — Demo', 'A regional operations pathway with scenario-based learning and turboprop-oriented crew preparation.', 'Kochi, India', 18, 6100000.00, 'INR', 18, 27, 55.00, 55.00, 55.00, 55.00, TRUE, TRUE, '2026-12-08', 'Application|Eligibility|Aptitude Test|Technical Assessment|Interview|Medical|Final Selection', 'OPEN'),
('NGA-08', 'NextGen Aviator Program', 'NovaFlight Institute — Demo', 'A technology-forward training route incorporating digital learning, modern simulators and analytics.', 'Chennai, India', 20, 6950000.00, 'INR', 18, 26, 60.00, 60.00, 60.00, 60.00, TRUE, TRUE, '2027-01-25', 'Application|Eligibility|Online Assessment|Simulator Assessment|Interview|Medical|Final Selection', 'UPCOMING'),
('GFT-09', 'Global Flight Training Pathway', 'Meridian Air Training — Demo', 'A fictional modular route for candidates seeking exposure to multiple training locations and procedures.', 'Johannesburg, South Africa', 24, 1180000.00, 'ZAR', 18, 30, 55.00, 55.00, 55.00, 55.00, TRUE, TRUE, '2027-02-18', 'Application|Eligibility|English Assessment|Interview|Medical|Final Selection', 'OPEN'),
('FST-10', 'Future Skies Cadet Programme', 'Orion Flight College — Demo', 'A comprehensive airline-readiness course with human factors, upset prevention and crew resource management.', 'Gold Coast, Australia', 24, 142000.00, 'AUD', 18, 27, 60.00, 60.00, 60.00, 60.00, TRUE, TRUE, '2027-03-01', 'Application|Eligibility|Aptitude Test|Group Exercise|Interview|Medical|Final Selection', 'UPCOMING');

