CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_number VARCHAR(30) NOT NULL UNIQUE,
    candidate_id BIGINT NOT NULL,
    program_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    current_step INTEGER NOT NULL DEFAULT 1,
    draft_data_json TEXT NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_applications_candidate FOREIGN KEY (candidate_id) REFERENCES users(id),
    CONSTRAINT fk_applications_program FOREIGN KEY (program_id) REFERENCES cadet_programs(id),
    CONSTRAINT uq_candidate_program UNIQUE (candidate_id, program_id),
    CONSTRAINT ck_application_step CHECK (current_step BETWEEN 1 AND 7)
);

CREATE TABLE application_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    changed_by BIGINT NOT NULL,
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_status_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT fk_status_actor FOREIGN KEY (changed_by) REFERENCES users(id)
);

CREATE TABLE selection_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    stage_order INTEGER NOT NULL,
    stage VARCHAR(80) NOT NULL,
    status VARCHAR(30) NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE,
    score NUMERIC(6,2),
    remarks TEXT,
    CONSTRAINT fk_stage_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT uq_application_stage UNIQUE (application_id, stage_order)
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL UNIQUE,
    content_type VARCHAR(120) NOT NULL,
    file_size BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    review_reason TEXT,
    reviewed_by BIGINT,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_documents_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT fk_documents_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    type VARCHAR(80) NOT NULL,
    title VARCHAR(180) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80),
    details TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES users(id)
);

CREATE INDEX idx_application_candidate_status ON applications(candidate_id, status);
CREATE INDEX idx_application_program_status ON applications(program_id, status);
CREATE INDEX idx_status_history_application ON application_status_history(application_id, created_at);
CREATE INDEX idx_documents_application_status ON documents(application_id, status);
CREATE INDEX idx_notifications_recipient_read ON notifications(recipient_id, is_read, created_at);
CREATE INDEX idx_audit_created_at ON audit_logs(created_at);

