CREATE TABLE assessment_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT,
    category VARCHAR(40) NOT NULL,
    question TEXT NOT NULL,
    option_a VARCHAR(300) NOT NULL,
    option_b VARCHAR(300) NOT NULL,
    option_c VARCHAR(300) NOT NULL,
    option_d VARCHAR(300) NOT NULL,
    correct_option VARCHAR(1) NOT NULL,
    points INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_question_program FOREIGN KEY (program_id) REFERENCES cadet_programs(id)
);

CREATE TABLE assessment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    score NUMERIC(6,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    answers_json TEXT NOT NULL,
    CONSTRAINT fk_attempt_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT fk_attempt_candidate FOREIGN KEY (candidate_id) REFERENCES users(id)
);

CREATE TABLE interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    mode VARCHAR(30) NOT NULL,
    location VARCHAR(300) NOT NULL,
    interviewer VARCHAR(120) NOT NULL,
    remarks TEXT,
    status VARCHAR(30) NOT NULL,
    CONSTRAINT fk_interview_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT fk_interview_candidate FOREIGN KEY (candidate_id) REFERENCES users(id)
);

CREATE INDEX idx_attempt_candidate ON assessment_attempts(candidate_id, submitted_at);
CREATE INDEX idx_interview_candidate ON interviews(candidate_id, scheduled_at);

INSERT INTO assessment_questions (category,question,option_a,option_b,option_c,option_d,correct_option,points) VALUES
('MATHEMATICS','An aircraft travels 360 nautical miles in 2 hours. What is its average ground speed?','160 knots','180 knots','200 knots','220 knots','B',10),
('MATHEMATICS','What is 15% of 480?','62','68','72','78','C',10),
('PHYSICS','Which force directly opposes drag in steady level flight?','Lift','Weight','Thrust','Gravity','C',10),
('PHYSICS','At constant mass, acceleration is directly proportional to which quantity?','Force','Volume','Density','Time','A',10),
('ENGLISH','Choose the grammatically correct sentence.','The crew are completed the checklist.','The crew has completed the checklist.','The crew completing the checklist.','The crew have complete the checklist.','B',10),
('APTITUDE','Complete the sequence: 3, 6, 12, 24, ?','30','36','42','48','D',10),
('APTITUDE','If all cadets are trainees and some trainees are graduates, which statement is certainly true?','All graduates are cadets','Some cadets are graduates','All cadets are trainees','No trainees are cadets','C',10),
('AVIATION','What does CRM commonly stand for in aviation?','Crew Resource Management','Cabin Route Mapping','Control Radar Mode','Crew Rotation Method','A',10),
('AVIATION','Which instrument primarily indicates altitude?','Airspeed indicator','Altimeter','Turn coordinator','Heading indicator','B',10),
('ENGLISH','Select the closest meaning of “meticulous.”','Careless','Thorough','Rapid','Uncertain','B',10);

